### ISSUE TITLE
Poderia ter usado um switch

### ISSUE THREAD

**Issue by eduardomarossi** [decoejz/APS2embarcados#2]
https://github.com/decoejz/APS2embarcados/blob/0cd9f138e96998a397ccbc9234e98b39b23b60fa/MXT_EXAMPLE_USART1/src/main.c#L115-L126

**Comment by Veguinho** [comment]
Corrigido!

**Comment by decoejz** [comment]
b9f7057d88c5bbd61bdfc41ca99f4ab9e065814f
