### ISSUE TITLE
Só utiliza interrupção de seg, porque verifica por alarme?

### ISSUE THREAD

**Issue by eduardomarossi** [decoejz/APS2embarcados#5]
https://github.com/decoejz/APS2embarcados/blob/0cd9f138e96998a397ccbc9234e98b39b23b60fa/MXT_EXAMPLE_USART1/src/main.c#L700-L702

**Comment by decoejz** [comment]
Concertado!

957719205d2b235d3a5f0d1ef9334ca4e354808a
