### ISSUE TITLE
Cenário 1 parcialmente (não para a máquina ao abrir porta, risco a criança)

### ISSUE THREAD

**Issue by eduardomarossi** [decoejz/APS2embarcados#6]
Aparece a mensagem "porta trancada". Mas vocês tem que pensar, que o porta aberta é um sensor que indica se a porta está aberta ou não (entrada), e não uma saída controlável.

Então se a porta está aberta, o ideal seria parar a lavagem/pausar.

**Comment by decoejz** [comment]
Mas isso não esta como pre requisito, apenas preciso garantir que nada aconteça com a máquina caso a criança queira brincar com ela enquanto esta acontecendo a lavagem. Garantimos que ela esta travada durante a lavagem.

**Comment by eduardomarossi** [comment]
Comentei sobre o tema em sala.

Para efeitos de rubrica neste projeto, não iremos exigir este requisito.
