### ISSUE TITLE
Cenário 1 parcial: Não tem como travar a máquina durante a lavagem

### ISSUE THREAD

**Issue by eduardomarossi** [decoejz/APS2embarcados#7]
O ícone do lock não aparece durante a contagem da lavagem.

E se você clica no canto da tela, a contagem trava.

**Comment by decoejz** [comment]
De fato precisamos desativar a área da tela referente ao bloqueio durante a lavagem, porém ela esta sempre travada quando uma lavagem esta acontecendo, já que não existe nenhuma possibilidade de ação nessa página.

**Comment by decoejz** [comment]
d791b6e70248256e17aa759ceb54a2c26675203c
